apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
  namespace: sensor-query
data:
  STORAGE_MODE: "hybrid"
  LOCAL_STORAGE_PATH: "/data/raw"
  LOCAL_ENABLE_CACHING: "true"
  
  AZURE_CONTAINER_NAME: "sensor-data-cold-storage"
  AZURE_CONNECTION_TIMEOUT: "30"
  AZURE_RETRY_ATTEMPTS: "3"
  AZURE_MAX_WORKERS: "8"
  
  MAX_QUERY_DURATION_HOURS: "168"
  DEFAULT_MAX_DATAPOINTS: "10000"
  MAX_ABSOLUTE_DATAPOINTS: "100000"
  DEFAULT_INTERVAL_MS: "1000"
  ENABLE_SMART_AGGREGATION: "true"
  QUERY_PARALLEL_WORKERS: "4"
  
  CACHE_ENABLED: "true"
  CACHE_SIZE_MB: "512"
  CACHE_TTL_SECONDS: "3600"
  CACHE_MAX_ENTRIES: "10000"
  
  RAW_TIER_MAX_HOURS: "24"
  AGGREGATED_TIER_MAX_HOURS: "168"
  DAILY_TIER_THRESHOLD_HOURS: "168"
  
  API_HOST: "0.0.0.0"
  API_PORT: "8080"
  API_WORKERS: "4"
  API_DEBUG: "false"
  LOG_LEVEL: "INFO"